name: CI/CD on Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v1
      - name: Run build script
        run: ./entrypoint.sh
        shell: bash
       # with:
        #  TOKEN: ${{ secrets.TOKEN }}
        env:
          SERVER: production
          TOKEN: ${{ secrets.TOKEN }}