name: CI/CD on Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v1
      - name: Run build script
        #run: ./entrypoint.sh
        run: |
          sudo apt-get install curl
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install nodejs
          # Check node version
          node -v 
          # v13.9.0
          # Also, check the npm version
          npm -v 
          ls
          #sh -c " 🔄Installing NPM"
          npm install

          #sh -c "🔄🎯Building"
          npm run build --if-present #:"$SERVER"

          #sh -c "🔄Installing firebase"
          npm install -g firebase-tools

          #sh -c "✅Deply to $SERVER"
          firebase deploy -P production --token "${{ secrets.TOKEN }}"
        shell: bash
       # with:
        #  TOKEN: ${{ secrets.TOKEN }}
        env:
          SERVER: production
          TOKEN: ${{ secrets.TOKEN }}
          CI: false