name: CI/CD on Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "JAVIER"
        env:
          SERVER: production
          TOKEN: ${{ secrets.TOKEN }}